# mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprort?serverTimezone=GMT%2b8
    username: root
    password: word
# mybatis基本配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
# 端口
server:
  port: 9000
